name: CI

on:
  push:
  schedule:
    - cron: '0 1 * * *' # Should test every day at 1AM, though apparently does not work anywhere but master branch
  
jobs:
  # Example of a test job, just prints Hello world
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo Hello world
  # Placeholder job for testing the processor, based on build job from https://github.com/bu-cms/bucoffea/blob/master/.github/workflows/pythonpackage.yml
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          # Install into base environment to avoid issue of environment variables not persisting between steps in a workflow, see https://autobencoder.com/2020-08-24-conda-actions/
          conda env update --file environment.yml --name base
      - name: Activate conda environment
        run: |
          curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh > conda-install.sh
          bash conda-install.sh
          conda create --name myenv python=3.8.3
          conda activate myenv
          conda install -y -c conda-forge ndcctools conda-pack dill xrootd coffea

      - name: Install package
        run: |
          pip install -e .
      - name: Run processors over test files
        run: |
          cd analysis/topEFT
          chmod +x ./check_yields.sh 
          ./check_yields.sh 
