name: CI

on:
  push:
  schedule:
    - cron: '0 1 * * *' # Should test every day at 1AM, though apparently does not work anywhere but master branch
  
jobs:
  # Example of a test job, just prints Hello world
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo Hello world



  # Placeholder job for testing the processor, based on build job from https://github.com/bu-cms/bucoffea/blob/master/.github/workflows/pythonpackage.yml
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package
        run: |
          pip install -e .

#      - name: Activate conda
#        run: |
#          printf "Activating conda environment..."
#          OUT_FILE_NAME="output_check_yields"
#          REF_FILE_NAME="test/ref_yields.json"
#          unset PYTHONPATH
#          export PYTHONPATH=
#          CONDA_BASE=$(conda info --base)
#          . $CONDA_BASE/etc/profile.d/conda.sh
#          echo "*** Install Conda and Pip packages"
#          conda update -n base -c defaults conda
#          conda create -y --name coffea-env
#          conda activate coffea-env
#          conda install -y python=3.8.3 six dill
#          conda install -y -c conda-forge coffea ndcctools conda-pack xrootd uproot

     # - name: Run processors over test files
     #   run: |
     #     cd analysis/topEFT
     #     time python run.py ../../topcoffea/cfg/check_yields_sample.cfg -o ${OUT_FILE_NAME}
     #     python get_yield_json.py -f histos/${OUT_FILE_NAME}.pkl.gz -n ${OUT_FILE_NAME} --quiet
     #     python comp_yields.py ${REF_FILE_NAME} ${OUT_FILE_NAME}.json -t1 "Ref yields" -t2 "New yields" --quiet
     #     echo $?
      - name: Run processors over test files
        run: |
          cd analysis/topEFT
          chmod +x ./check_yields.sh 
          ./check_yields.sh 
