name: CI

on:
  push:
  schedule:
    - cron: '0 1 * * *' # Should test every day at 1AM, though apparently does not work anywhere but master branch
  
jobs:
  # Example of a test job, just prints Hello world
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo Hello world


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: install package
#        run: |
#          pip install -e .

      - name: Run processors over test files
        run: |
          cd analysis/topEFT
          chmod +x ./check_yields.sh 
          ./check_yields.sh 
