name: CI

on:
  push:
  schedule:
    - cron: '0 1 * * *' # Should test every day at 1AM, though apparently does not work anywhere but master branch
  
jobs:
  # Example of a test job, just prints Hello world
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo Hello world

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base

      - name: Will this work
        run: |
          conda list

      - name: install package
        run: |
          pip install -e .

      - name: download root files
        run: |
          curl http://www.crc.nd.edu/~ywan2/root_files/json_root_files.sh

      - name: Run processors over test files
        run: |
          cd analysis/topEFT
          time python run.py ../../topcoffea/cfg/check_yields_sample.cfg -o output_check_yields

      - name: Get Yeilds 
        run: |
          cd analysis/topEFT
          python get_yield_json.py -f histos/output_check_yields.pkl.gz -n output_check_yields --quiet

      - name: Compare Yeilds
        run: |
          cd analysis/topEFT
          python comp_yields.py test/ref_yields.json output_check_yields.json -t1 "Ref yields" -t2 "New yields" --quiet

#          chmod +x ./check_yields.sh
#          ./check_yields.sh 
