name: CI

on: push

stages:
- stage: A

  jobs:
  
    Activate_Conda:
      stage: stage-1
      needs: []
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Add conda to system path
          run: |
            echo $CONDA/bin >> $GITHUB_PATH

        - name: Install dependencies
          run: |
            conda env update --file environment.yml --name base

        - name: Conda list
          run: |
            conda list

    Submit_Workers:
      stage: stage-1
      needs: [Activate_Conda]
      needs: Activate_Conda
      runs-on: ubuntu-latest
      steps:
        - name: Submit workers
          run: |
            work_queue_worker -M $USER-wq-topcoffea --single-shot
