name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo Hello world

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package
        run: |
          pip install -e .

      - name: Run processors over test files
        run: |
          cd analysis/topEFT
          chmod +x ./check_yields2.sh
          ./check_yields2.sh 
