
on:
  push:

   jobs:
     Full_analysis:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name:
            run: | 
              bash test_background.sh
